name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-deploy:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout code
        id: checkout
        uses: actions/checkout@v1

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v3
        id: build-image
        env:
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: mastodon
          IMAGE_TAG: latest
